# Config file for CelebA dataset (200k)

output_dir: './data/hzh/checkpoints/StyleGAN.pytorch/ckp_ffhq_1'
structure: 'linear'
checkpoint_factor: 4
feedback_factor: 4
dataset:
  img_dir: '/kaggle/input/ffhq-face-data-set/thumbnails128x128/'
  folder: False
  resolution: 128
sched:
  epochs: [8,16,32,32,64,64]
